FROM gs-worker-host AS worker-host

FROM microsoft/dotnet:2.1-sdk AS build
COPY . /src
WORKDIR /src/Src/GlobalSearch.Worker.Single.Executor

RUN dotnet publish -c Release -o /tmp/app

FROM microsoft/dotnet:2.1-aspnetcore-runtime AS aspnetcore

FROM aspnetcore AS final
WORKDIR /app

COPY --from=worker-host /app .
COPY --from=build /tmp/app .
COPY --from=build /src/Src/GlobalSearch.Worker.Single.Executor/appsettings.json .

ENTRYPOINT ["dotnet", "Cloud.WorkerHost.dll"]