FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src

COPY . .

WORKDIR /src/Ref/Cloud.WorkerHost
RUN dotnet publish -c Release -o /tmp/app

FROM base AS final
WORKDIR /app
COPY --from=build /tmp/app .