FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY . .

WORKDIR /src/Src/GlobalSearch.IndexingService
RUN dotnet publish -c Release -o /build

FROM base AS final
WORKDIR /app
COPY --from=build /build .
COPY --from=build /src/Src/GlobalSearch.IndexingService/log4net.debug.config .

ENTRYPOINT ["dotnet", "GlobalSearch.IndexingService.dll"]